// src/lib/chatDB/schema.ts
import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const chatSchema = appSchema({
  version: 7,
  tables: [
    tableSchema({
      name: 'messages',
      columns: [
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'sender_id', type: 'string', isIndexed: true },
        { name: 'message_uid', type: 'string', isOptional: true, isIndexed: true },
        { name: 'client_msg_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'content', type: 'string', isOptional: true },
        { name: 'original', type: 'string', isOptional: true },
        { name: 'translated_text', type: 'string', isOptional: true },
        { name: 'translated_by_tier', type: 'string', isOptional: true },
        { name: 'link_preview', type: 'string', isOptional: true },
        { name: 'link_preview_url', type: 'string', isOptional: true, isIndexed: true },
        { name: 'link_preview_status', type: 'string', isOptional: true },
        { name: 'meta', type: 'string', isOptional: true },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'reply_to_message_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'reply_to', type: 'string', isOptional: true, isIndexed: true },
        { name: 'media_url', type: 'string', isOptional: true, isIndexed: true },
        { name: 'media_width', type: 'number', isOptional: true },
        { name: 'media_height', type: 'number', isOptional: true },
        { name: 'media_aspect', type: 'number', isOptional: true },
        { name: 'media_mime', type: 'string', isOptional: true },
        { name: 'media_provider', type: 'string', isOptional: true },
        { name: 'room_seq', type: 'number', isOptional: true, isIndexed: true },
        { name: 'delete_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'moment_config', type: 'string', isOptional: true },
        { name: 'deleted_for_all_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'deleted_for_all_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'kind', type: 'string' },
        { name: 'is_notice', type: 'boolean', isOptional: true },
        { name: 'notice_pinned_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'unread_count', type: 'number', isOptional: true },

        // secure v1 receive/store
        { name: 'is_secure', type: 'boolean', isOptional: true, isIndexed: true },
        { name: 'secure_epoch', type: 'number', isOptional: true, isIndexed: true },
        { name: 'secure_sender_device_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'cipher_suite', type: 'string', isOptional: true },
        { name: 'ciphertext', type: 'string', isOptional: true },
        { name: 'nonce', type: 'string', isOptional: true },
        { name: 'aad_version', type: 'number', isOptional: true },
        { name: 'secure_meta', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'chat_attachments',
      columns: [
        { name: 'message_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'message_uid', type: 'string', isOptional: true, isIndexed: true },
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'sort_order', type: 'number', isOptional: true },
        { name: 'type', type: 'string', isOptional: true },
        { name: 'url', type: 'string' },
        { name: 'thumb_url', type: 'string', isOptional: true },
        { name: 'mime', type: 'string', isOptional: true },
        { name: 'width', type: 'number', isOptional: true },
        { name: 'height', type: 'number', isOptional: true },
        { name: 'aspect', type: 'number', isOptional: true },
        { name: 'duration_ms', type: 'number', isOptional: true },
        { name: 'file_name', type: 'string', isOptional: true },
        { name: 'file_size', type: 'number', isOptional: true },
        { name: 'provider', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rooms',
      columns: [
        { name: 'title', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'last_msg', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'unread_count', type: 'number', isOptional: true },
        { name: 'is_pinned', type: 'boolean', isOptional: true },
        { name: 'member_count', type: 'number', isOptional: true },
        { name: 'type', type: 'string', isOptional: true, isIndexed: true },
        { name: 'subtype', type: 'string', isOptional: true },
        { name: 'beacon_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'business_id', type: 'string', isOptional: true },
      ],
    }),

    tableSchema({
      name: 'room_read_states',
      columns: [
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'last_read_seq', type: 'number', isIndexed: true },
        { name: 'is_active', type: 'boolean', isOptional: true, isIndexed: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'nickname', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
      ],
    }),

    tableSchema({
      name: 'message_bookmarks',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'message_uid', type: 'string', isIndexed: true },
        { name: 'message_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'room_seq', type: 'number', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'last_error', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'message_reactions',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'message_uid', type: 'string', isIndexed: true },
        { name: 'message_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'room_seq', type: 'number', isOptional: true, isIndexed: true },
        { name: 'reaction_key', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'deleted_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'sync_state', type: 'string', isIndexed: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'last_error', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'message_reaction_counts',
      columns: [
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'message_uid', type: 'string', isIndexed: true },
        { name: 'reaction_key', type: 'string', isIndexed: true },
        { name: 'count', type: 'number' },
        { name: 'updated_at', type: 'number', isIndexed: true },
      ],
    }),

    tableSchema({
      name: 'room_open_snapshots',
      columns: [
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'items_json', type: 'string' },
        { name: 'last_seq', type: 'number', isOptional: true, isIndexed: true },
        { name: 'tail_signature', type: 'string', isOptional: true },
        { name: 'item_count', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'message_translations',
      columns: [
        { name: 'message_id', type: 'string', isIndexed: true },
        { name: 'room_id', type: 'number', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'purpose', type: 'string', isIndexed: true },
        { name: 'from_mode', type: 'string', isOptional: true },
        { name: 'tone', type: 'string', isOptional: true },
        { name: 'provider', type: 'string', isOptional: true },
        { name: 'target_lang', type: 'string' },
        { name: 'generated_tier', type: 'string' },
        { name: 'translated_text', type: 'string' },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});

export default chatSchema;
